macro(slime_option var default_value description)
    if(DEFINED ENV{${var}})
        if("$ENV{${var}}" MATCHES "^(ON|OFF|TRUE|FALSE)$")
            set(_default "$ENV{${var}}")
        else()
            message(WARNING "Invalid value for env ${var}: '$ENV{${var}}', use default ${default_value}")
            set(_default ${default_value})
        endif()
    else()
        set(_default ${default_value})
    endif()
    option(${var} "${description}" ${_default})
endmacro()
